org: ayanguha
app: dqf
service: dqf

frameworkVersion: '2 || 3'

custom:
  wsgi:
    app: app.server
  apigwBinary:
    types:
      - "*/*"
  pythonRequirements:
    dockerizePip: true
    useDownloadCache: false
    useStaticCache: false
    slim: true
    slimPatternsAppendDefaults: false
    slimPatterns:
      - '**/*.py[c|o]'
      - '**/__pycache__*'

provider:
  name: aws
  runtime: python3.8
  profile: modelapi
  region: ap-southeast-2
  stage: dev
  memorySize: 512
  

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-apigw-binary
